# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: DCN - SandBox
author: Saphety
logo: images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Define your Binder to run code
launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)

# Information about where the book exists on the web
repository:
  url: https://github.com/sggodinho/dcn-sandbox-api-notebooks  # Online location of your book
  path_to_book: "notebooks"  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
